### ISSUE TITLE
Webooks: Cannot validate signature with `/app` router `POST` requests

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/next-sanity#459] opened 2023-06-16 13:09 UTC
In the readme, Sanity suggests to verify the signature using the following code:

```js
// /app/api/webhook/route.ts

import { parseBody } from "next-sanity/webhook";

export async function POST(req: Request) {
const { body, isValidSignature } = await parseBody(req, process.env.SANITY_WEBHOOK_SECRET);
...
}
```

However, while using it with Next.js API routes inside /app route, it throws the following error.

```
Argument of type 'Request' is not assignable to parameter of type 'NextApiRequest'.
  Type 'Request' is missing the following properties from type 'NextApiRequest': query, cookies, env, aborted, and 51 more.ts(2345)
```

How can I verify the signature and parse the webhook as expected when using the /app router?

**Comment by mavic111** [comment] 2023-06-16 19:57
I do like this

```javascript
import { NextRequest } from "next/server";
import { isValidSignature, SIGNATURE_HEADER_NAME } from "@sanity/webhook";

const secret = process.env.SANITY_REVALIDATE_SECRET;

export async function POST(req: NextRequest) {
  try {
    const signature = req.headers.get(SIGNATURE_HEADER_NAME);
    const body: PostRequest = await req.json();
    if (
      secret &&
      signature &&
      !isValidSignature(JSON.stringify(body), signature, secret)
    ) {
      return (
        NextResponse.json({
          success: false,
          message: "Invalid signature",
          apiVersion: apiVersion,
          useCdn: useCdn,
        }),
        {
          status: 401,
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    }
    ...
}
```

**Comment by surjithctly** [comment] 2023-06-17 09:01
Thanks for the workaround @mavic111 , since Sanity supports webhooks directly in the **next-sanity** plugin, I think they should support this. Will keep the issue open for them to decide.

**Comment by mavic111** [comment] 2023-06-21 13:03
My pull request about this is already merged. Can you confirm if it works?

**Comment by surjithctly** [comment] 2023-06-21 13:53
I'm not able to test now, but you can close this if it works for you. It's better the docs are also adjusted to convey the update.

**Comment by mavic111** [comment] 2023-06-21 16:42
Now, the parseBody function can receive `NextRequest` type, 

But it still not works to validate secret, because `req instanceof NextRequest` is returning false in the route handler. It makes the parseBody function not works as intended.

```js
import { NextRequest } from 'next/server'

let next_request = new NextRequest('https://nextjs.org')
console.log('1', next_request instanceof NextRequest) // returning true


export async function GET(req: NextRequest) {
  console.log('2', req instanceof NextRequest) // returning false
  return NextResponse.json({ isNextRequest: req instanceof NextRequest })
}
```

**Comment by surjithctly** [comment] 2023-07-06 06:40
your merge is now reverted. Not sure why!

**Comment by stipsan** [comment] 2023-08-07 17:56
> your merge is now reverted. Not sure why!

We got reports that it wasn't working for folks, and we didn't have bandwidth to investigate as we were busy wrapping up the new [Perspectives](https://www.sanity.io/blog/introducing-perspectives-sanity-previews) and [Live Preview](https://www.sanity.io/blog/preview-everything-everywhere-all-at-once) features before the team went off on PTO for the summer 🙌 
And so we reverted it, and once back from vacation we would look at this and E2E properly in our [app-router template](https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website). 

We've added back @mavic111's awesome `parseAppBody` in [v5.2.0](https://github.com/sanity-io/next-sanity/releases/tag/v5.2.0) and we'll update the docs for it soon, we're currently doing QA and end-to-end on it 🙌 

Thanks again for your contributions @mavic111 🥳

**Closed** 2023-08-19 03:19 UTC
Labels: triaged
