### ISSUE TITLE
Type error: Module '"sanity"' has no exported member 'defineConfig'.

### ISSUE THREAD

**Issue by RonAlmog** [sanity-io/next-sanity#329] opened 2023-02-08 16:04 UTC
next13, getting this error on build:
Type error: Module '"sanity"' has no exported member 'defineConfig'.
my sanity.config.ts:
```
import {defineConfig} from 'sanity'
import {deskTool} from 'sanity/desk'
import {visionTool} from '@sanity/vision'
import {schemaTypes} from './schemas'

export default defineConfig({
  name: 'default',
  title: 'portfolio',

  projectId: '123xyz',
  dataset: 'production',

  plugins: [deskTool(), visionTool()],

  schema: {
    types: schemaTypes,
  },
})

```
Any idea?
versions from my package.json:
```
"next": "13.1.6",
"next-sanity": "^4.1.2",
```

**Comment by Nick-h4ck3r** [comment] 2023-02-11 12:17
I'm facing the same issue. Works fine in local environment though.

**Comment by girishmt4** [comment] 2023-02-21 04:50
Did anyone find any solution to this issue? Seems like next-sanity does not support nextjs13 yet. Hope it gets fixed soon

**Comment by marionjudy13** [comment] 2023-03-15 15:14
I'm also having this issue... Has anyone had any luck fixing it?

**Comment by girishmt4** [comment] 2023-03-15 15:43
I had the same issue. You must be having another sanity.ts file in the root directory. That's why it tries to find 'defineConfig' in that file. Either rename that file or better move that file to another 'lib' folder and reorganize the imports.
It started working for me...

**Comment by stipsan** [comment] 2023-05-24 19:23
Closing as we're unable to reproduce. The reported cases are most likely caused by what @girishmt4 outlines in [his reply](https://github.com/sanity-io/next-sanity/issues/329#issuecomment-1470278788) :)

**Closed by stipsan** 2023-05-24 19:23 UTC
Labels: triaged
