### ISSUE TITLE
Next.js App on Vercel is failing to build after next-sanity update

### ISSUE THREAD

**Issue by alexanderkalachev** [sanity-io/next-sanity#664] opened 2023-10-08 18:50 UTC
After package update project is failing to build.
Cross origins is set, nothing else seemingly changed. Cannot figure out what is causing the issue.

Here is full build log:
```
[21:40:17.679] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[21:40:17.776] Cloning github.com/alexanderkalachev/weresk-monorepo (Branch: main, Commit: 2472959)
[21:40:18.333] Cloning completed: 556.442ms
[21:40:25.803] Restored build cache
[21:40:25.874] Running "vercel build"
[21:40:26.521] Vercel CLI 32.4.1
[21:40:26.772] > Detected Turbo. Adjusting default settings...
[21:40:27.208] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[21:40:27.214] Running "install" command: `pnpm install`...
[21:40:28.963] Scope: all 15 workspace projects
[21:40:31.182] ../../../..                              | Progress: resolved 1, reused 0, downloaded 0, added 0
[21:40:31.342] ../../../..                              | +304 -313 +++++++++++++--------------
[21:40:32.184] ../../../..                              | Progress: resolved 304, reused 0, downloaded 123, added 114
[21:40:33.184] ../../../..                              | Progress: resolved 304, reused 0, downloaded 138, added 127
[21:40:34.186] ../../../..                              | Progress: resolved 304, reused 0, downloaded 147, added 136
[21:40:35.227] ../../../..                              | Progress: resolved 304, reused 0, downloaded 181, added 176
[21:40:36.228] ../../../..                              | Progress: resolved 304, reused 0, downloaded 205, added 193
[21:40:37.230] ../../../..                              | Progress: resolved 304, reused 0, downloaded 243, added 232
[21:40:38.230] ../../../..                              | Progress: resolved 304, reused 0, downloaded 288, added 275
[21:40:39.231] ../../../..                              | Progress: resolved 304, reused 0, downloaded 303, added 303
[21:40:40.216] ../../../..                              | Progress: resolved 304, reused 0, downloaded 303, added 304, done
[21:40:41.898] 
[21:40:41.898] dependencies:
[21:40:41.898] + @weresk/core 0.0.0 <- ../../../../weresk/@weresk-core
[21:40:41.898] + @weresk/maket 0.0.0 <- ../../../../weresk/@weresk-maket
[21:40:41.898] - next 13.5.2
[21:40:41.898] + next 13.5.4
[21:40:41.900] - next-sanity 5.5.4
[21:40:41.900] + next-sanity 5.5.5
[21:40:41.900] - sanity 3.16.7
[21:40:41.900] + sanity 3.17.0
[21:40:41.900] 
[21:40:41.900] devDependencies:
[21:40:41.900] + @types/negotiator 0.6.1
[21:40:41.900] - @types/react 18.2.5
[21:40:41.900] + @types/react 18.2.25
[21:40:41.900] - @types/react-dom 18.2.3
[21:40:41.900] + @types/react-dom 18.2.10
[21:40:41.900] - tsconfig 7.0.0
[21:40:41.901] + tsconfig 0.0.0 <- ../../../../dev/tsconfig
[21:40:41.901] - typescript 4.9.5
[21:40:41.901] + typescript 5.2.2
[21:40:41.901] 
[21:40:41.981] Done in 14.7s
[21:40:42.037] Detected Next.js version: 13.5.4
[21:40:42.038] Running "turbo run build"
[21:40:42.510] • Packages in scope: @cs/culturaweek
[21:40:42.510] • Running build in 1 packages
[21:40:42.511] • Remote caching enabled
[21:40:42.691] @cs/culturaweek:build: cache miss, executing 69e06354155be8ca
[21:40:43.205] @cs/culturaweek:build: 
[21:40:43.205] @cs/culturaweek:build: > @cs/culturaweek@1.0.0 build /vercel/path0/projects/culturasaatio/apps/culturaweek
[21:40:43.206] @cs/culturaweek:build: > next build
[21:40:43.206] @cs/culturaweek:build: 
[21:40:43.977] @cs/culturaweek:build:    Creating an optimized production build ...
[21:41:08.149] @cs/culturaweek:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (167kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
[21:41:22.892] @cs/culturaweek:build:  ✓ Compiled successfully
[21:41:22.893] @cs/culturaweek:build:    Linting and checking validity of types ...
[21:41:33.520] @cs/culturaweek:build:    Collecting page data ...
[21:41:37.222] @cs/culturaweek:build:    Generating static pages (0/96) ...
[21:41:44.979] @cs/culturaweek:build: Error: Request error while attempting to reach https://96e1dixo.api.sanity.io/v2023-10-05/data/query/production?query=*%5B_type+%3D%3D+%27app%27+%26%26+_id+%3D%3D+%24appName%5D%5B0%5D%7B%0A++++languages%5B%5D%2C%0A++++header+%7B%0A++++++++...%2C%0A++++++++links%5B%5D-%3E%2C%0A++++++++marker+%7B%0A++++++++++++...%2C%0A++++++++++++link+%7B%0A++++++++++++++++%0A++++...%2C%0A++++file%7B%0A++++++++...%2C%0A++++++++%22url%22%3A+asset-%3Eurl%0A++++%7D%2C%0A++++reference-%3E%0A%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%2C%0A++++footer+%7B%0A++++++++...%2C%0A++++++++links%5B%5D-%3E%2C%0A++++++++contacts+%7B%0A++++++++++++...%2C%0A++++++++++++%0A++++fi%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%2C%0A++++ru%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%2C%0A++++en%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%0A%0A++++++++%7D%0A++++%7D%2C%0A++++hero+%7B%0A++++++++hideFooter%0A++++%7D%2C%0A++++palette-%3E%0A%7D&%24appName=%22culturaweek%22
[21:41:44.980] @cs/culturaweek:build:     at _.onerror (/vercel/path0/projects/culturasaatio/apps/culturaweek/.next/server/chunks/919.js:1:183074)
[21:41:44.980] @cs/culturaweek:build:     at /vercel/path0/projects/culturasaatio/apps/culturaweek/.next/server/chunks/919.js:1:182461 {
[21:41:44.980] @cs/culturaweek:build:   isNetworkError: true,
[21:41:44.980] @cs/culturaweek:build:   request: {
[21:41:44.980] @cs/culturaweek:build:     timeout: { connect: 300000, socket: 300000 },
[21:41:44.980] @cs/culturaweek:build:     maxRedirects: 0,
[21:41:44.984] @cs/culturaweek:build:     method: 'GET',
[21:41:44.985] @cs/culturaweek:build:     uri: '/data/query/production?query=*%5B_type+%3D%3D+%27app%27+%26%26+_id+%3D%3D+%24appName%5D%5B0%5D%7B%0A++++languages%5B%5D%2C%0A++++header+%7B%0A++++++++...%2C%0A++++++++links%5B%5D-%3E%2C%0A++++++++marker+%7B%0A++++++++++++...%2C%0A++++++++++++link+%7B%0A++++++++++++++++%0A++++...%2C%0A++++file%7B%0A++++++++...%2C%0A++++++++%22url%22%3A+asset-%3Eurl%0A++++%7D%2C%0A++++reference-%3E%0A%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%2C%0A++++footer+%7B%0A++++++++...%2C%0A++++++++links%5B%5D-%3E%2C%0A++++++++contacts+%7B%0A++++++++++++...%2C%0A++++++++++++%0A++++fi%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%2C%0A++++ru%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%2C%0A++++en%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%0A%0A++++++++%7D%0A++++%7D%2C%0A++++hero+%7B%0A++++++++hideFooter%0A++++%7D%2C%0A++++palette-%3E%0A%7D&%24appName=%22culturaweek%22',
[21:41:44.985] @cs/culturaweek:build:     json: true,
[21:41:44.985] @cs/culturaweek:build:     body: undefined,
[21:41:44.985] @cs/culturaweek:build:     query: false,
[21:41:44.985] @cs/culturaweek:build:     headers: { Accept: 'application/json' },
[21:41:44.985] @cs/culturaweek:build:     token: undefined,
[21:41:44.985] @cs/culturaweek:build:     tag: undefined,
[21:41:44.985] @cs/culturaweek:build:     perspective: undefined,
[21:41:44.985] @cs/culturaweek:build:     resultSourceMap: undefined,
[21:41:44.985] @cs/culturaweek:build:     canUseCdn: true,
[21:41:44.985] @cs/culturaweek:build:     signal: undefined,
[21:41:44.985] @cs/culturaweek:build:     fetch: undefined,
[21:41:44.985] @cs/culturaweek:build:     useAbortSignal: false,
[21:41:44.986] @cs/culturaweek:build:     url: 'https://96e1dixo.api.sanity.io/v2023-10-05/data/query/production?query=*%5B_type+%3D%3D+%27app%27+%26%26+_id+%3D%3D+%24appName%5D%5B0%5D%7B%0A++++languages%5B%5D%2C%0A++++header+%7B%0A++++++++...%2C%0A++++++++links%5B%5D-%3E%2C%0A++++++++marker+%7B%0A++++++++++++...%2C%0A++++++++++++link+%7B%0A++++++++++++++++%0A++++...%2C%0A++++file%7B%0A++++++++...%2C%0A++++++++%22url%22%3A+asset-%3Eurl%0A++++%7D%2C%0A++++reference-%3E%0A%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%2C%0A++++footer+%7B%0A++++++++...%2C%0A++++++++links%5B%5D-%3E%2C%0A++++++++contacts+%7B%0A++++++++++++...%2C%0A++++++++++++%0A++++fi%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%2C%0A++++ru%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%2C%0A++++en%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%0A%0A++++++++%7D%0A++++%7D%2C%0A++++hero+%7B%0A++++++++hideFooter%0A++++%7D%2C%0A++++palette-%3E%0A%7D&%24appName=%22culturaweek%22',
[21:41:44.986] @cs/culturaweek:build:     proxy: undefined,
[21:41:44.986] @cs/culturaweek:build:     withCredentials: false,
[21:41:44.986] @cs/culturaweek:build:     attemptNumber: 5
[21:41:44.986] @cs/culturaweek:build:   }
[21:41:44.986] @cs/culturaweek:build: }
[21:41:46.210] @cs/culturaweek:build: 
[21:41:46.210] @cs/culturaweek:build:  ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "https://cs-culturaweek-a0zhu4aje-culturasaatio.vercel.app". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
[21:41:46.439] @cs/culturaweek:build: 
[21:41:46.439] @cs/culturaweek:build:  ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "https://cs-culturaweek-a0zhu4aje-culturasaatio.vercel.app". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
[21:41:46.439] @cs/culturaweek:build: 
[21:41:46.439] @cs/culturaweek:build:  ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "https://cs-culturaweek-a0zhu4aje-culturasaatio.vercel.app". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
[21:41:46.605] @cs/culturaweek:build: 
[21:41:46.606] @cs/culturaweek:build: Error occurred prerendering page "/fi/tapahtumat/teatteri_0210". Read more: https://nextjs.org/docs/messages/prerender-error
[21:41:46.606] @cs/culturaweek:build: Error: Request error while attempting to reach https://96e1dixo.api.sanity.io/v2023-10-05/data/query/production?query=*%5B_type+%3D%3D+%27app%27+%26%26+_id+%3D%3D+%24appName%5D%5B0%5D%7B%0A++++languages%5B%5D%2C%0A++++header+%7B%0A++++++++...%2C%0A++++++++links%5B%5D-%3E%2C%0A++++++++marker+%7B%0A++++++++++++...%2C%0A++++++++++++link+%7B%0A++++++++++++++++%0A++++...%2C%0A++++file%7B%0A++++++++...%2C%0A++++++++%22url%22%3A+asset-%3Eurl%0A++++%7D%2C%0A++++reference-%3E%0A%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%2C%0A++++footer+%7B%0A++++++++...%2C%0A++++++++links%5B%5D-%3E%2C%0A++++++++contacts+%7B%0A++++++++++++...%2C%0A++++++++++++%0A++++fi%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%2C%0A++++ru%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%2C%0A++++en%5B%5D+%7B%0A++++++++%0A++++...%2C%0A++++markDefs%5B%5D+%7B%0A++++++++...%2C%0A++++++++file%7B%0A++++++++++++...%2C%0A++++++++++++%22url%22%3A+asset-%3Eurl%0A++++++++%7D%2C%0A++++++++reference-%3E%0A++++%7D%0A%0A++++%7D%0A%0A++++++++%7D%0A++++%7D%2C%0A++++hero+%7B%0A++++++++hideFooter%0A++++%7D%2C%0A++++palette-%3E%0A%7D&%24appName=%22culturaweek%22
[21:41:46.607] @cs/culturaweek:build:     at _.onerror (/vercel/path0/projects/culturasaatio/apps/culturaweek/.next/server/chunks/919.js:1:183074)
[21:41:46.607] @cs/culturaweek:build:     at /vercel/path0/projects/culturasaatio/apps/culturaweek/.next/server/chunks/919.js:1:182461
[21:41:51.399] @cs/culturaweek:build: 
   Generating static pages (24/96) 
[21:41:55.784] @cs/culturaweek:build: 
   Generating static pages (48/96) 
[21:41:59.673] @cs/culturaweek:build: 
   Generating static pages (72/96) 
[21:42:03.368] @cs/culturaweek:build: 
 ✓ Generating static pages (96/96) 
[21:42:03.370] @cs/culturaweek:build: 
[21:42:03.370] @cs/culturaweek:build: > Export encountered errors on following paths:
[21:42:03.370] @cs/culturaweek:build: 	/(user)/[lang]/(pages)/(event)/tapahtumat/[slug]/page: /fi/tapahtumat/teatteri_0210
[21:42:03.443] @cs/culturaweek:build:  ELIFECYCLE  Command failed with exit code 1.
[21:42:03.466] @cs/culturaweek:build: ERROR: command finished with error: command (/vercel/path0/projects/culturasaatio/apps/culturaweek) pnpm run build exited (1)
[21:42:03.468] @cs/culturaweek#build: command (/vercel/path0/projects/culturasaatio/apps/culturaweek) pnpm run build exited (1)
[21:42:03.469]  ERROR  run failed: command  exited (1)
[21:42:03.469] 
[21:42:03.470]   Tasks:    0 successful, 1 total
[21:42:03.470]  Cached:    0 cached, 1 total
[21:42:03.470]    Time:    1m21.331s 
[21:42:03.470] Summary:    /vercel/path0/.turbo/runs/2WUc8q1U9qdJhnl9EkPLLLrO5AA.json
[21:42:03.470]  Failed:    @cs/culturaweek#build
[21:42:03.471] 
[21:42:03.481] Error: Command "turbo run build" exited with 1
```

**Comment by stipsan** [comment] 2023-10-09 07:51
Looks like you hit a temporary rate limit error. That's not expected to happen from a static generation build process like yours. Was it a one-off or is it still happening?

**Comment by alexanderkalachev** [comment] 2023-10-09 08:32
@stipsan Yes, it is. Also I have previous edition of this app working in another project on Vercel and it is working.

**Comment by stipsan** [comment] 2023-10-09 09:02
Sorry to hear that! I recommend reaching out to our support staff [at the Community Slack](https://slack.sanity.io/). Let them know the previous version of `next-sanity` you were on before you upgraded to `latest` as it's important context for them. There are certain defaults that changed in `@sanity/client` in the last 3 major versions, [like automatic retrying of certain errors](https://github.com/sanity-io/client/pull/199). Your Node.js and Next.js versions are also relevant.

**Comment by alexanderkalachev** [comment] 2023-10-10 20:05
@stipsan Thank you! But seems like it's not that. I set maxRetries to zero and the error remains. Also, the breaking change in @sanity/client was before the newer version just fine.
How did you understand that it's about temporary rate limit?

**Comment by stipsan** [comment] 2023-10-10 20:50
That's unfortunate 😅 Are you able to create a reproduction repository we can look at and dive in?

Regarding temporary rate limit, that was an assumption on my end because of:
```
attemptNumber: 5
```
in your log. I've since been told this can also happen if the request is timing out, and isn't proof exclusive that it's a rate limit case.

**Comment by alexanderkalachev** [comment] 2023-10-10 20:54
Thank you! I will try to isolate a problem and create a separate repository.

**Comment by alexanderkalachev** [comment] 2023-10-10 21:51
https://github.com/alexanderkalachev/sanity-access-issue
Because this app is a part of bigger monorepo, I isolated it in separate repository and changed Sanity project to sample.
In development it works ok, but when trying to deploy on Vercel fails with the same error.

When deploying, add those two variables:
NEXT_PUBLIC_APP_NAME=sample
NEXT_PUBLIC_SANITY_PROJECT_ID=l8qcb7zz

Also. When I was preparing this repository, once in a while Vercel was able to build it, but on the next deploy – error pops up again.

**Comment by charlottedamm** [comment] 2023-10-11 07:58
We're having the same issue. Our setup is similar (Next.js 13 app directory with turbo, deploying on Vercel). However, our issue started 2 days before we upgraded next-sanity. So unsure if this package is the issue.
Our build started failing with the same error on October 6th. Downgrading all the package upgrades to the October 5th state did not work - sometimes the build works, but most of the time it fails at the generating static pages step with a network error. It makes no sense - the query return data with no authentication.

**Comment by alexanderkalachev** [comment] 2023-10-11 09:09
Having exactly the same behaviour and similar timing

**Comment by stipsan** [comment] 2023-10-12 06:32
@alexanderkalachev thanks so much for sharing the report! Also thanks for sharing @charlottedamm, given you started experiencing the same without updating the package 🤔
I'll escalate this internally and keep you posted 👍

**Comment by stipsan** [comment] 2023-10-12 11:17
Hey, @charlottedamm and @alexanderkalachev could you try using `cache: "no-store"` to see if it resolves the build errors? If so, then it's a signal that the traffic coming from the [Vercel Data Cache](https://vercel.com/docs/infrastructure/data-cache) is high enough, and on few enough IP addresses that it triggers our IP rate limit.

Example:
```ts
import {createClient} from 'next-sanity'

const client = createClient({
  projectId,
  dataset,
  apiVersion,
  useCdn: false,
  perspective: 'published'
})

const data = await client.fetch(query, params, {
  cache: 'no-store',
})
```

If it turns out to be the case, you can use this as a workaround until we find a proper solution on our end:

```diff
import {createClient} from 'next-sanity'

const client = createClient({
  projectId,
  dataset,
  apiVersion,
- useCdn: false,
+ useCdn: true,
  perspective: 'published'
})

const data = await client.fetch(query, params, {
  cache: 'no-store',
})
```
Setting `useCdn: true` is to guard against blowing up your rate limit since your application is built with its own cache layer until now, and when `cache: 'no-store'` is used you should expect to see an increase in API calls and it'll disable some of the cache layers.

To better understand how these settings change how your application fetches data and how it behaves, add this to your `next.config.js`:
```diff
/** @type {import('next').NextConfig} */
const nextConfig = {
+ experimental: {
+   logging: {
+     level: 'verbose',
+   },
+ },
}

module.exports = nextConfig
```
Now you'll see much more information when using `next dev`. You may add `fullUrl: true` to `experimental.logging` to see exactly which Content Lake API requests are being made and when.

**Comment by charlottedamm** [comment] 2023-10-12 14:08
We already have useCdn set to true in our sanity client

**Comment by stipsan** [comment] 2023-10-12 18:07
@charlottedamm I understand. How about `cache: 'no-store'`?

**Comment by stipsan** [comment] 2023-10-12 18:09
@charlottedamm do you mind sharing your `projectId` and `dataset` with me on cody@sanity.io so we can look it up in our error logs?

**Comment by Culturalist** [comment] 2023-10-12 18:20
@stipsan Yep, with "cache: no-store" project was able to be deployed.

**Comment by alexanderkalachev** [comment] 2023-10-12 18:21
@stipsan Yep, with "cache: no-store" project was able to be deployed

**Comment by ja-iy** [comment] 2023-10-12 21:30
Hi I have the same problem when using the current versions of next ( 13.5.4 ) and next sanity ( 5.5.8 ), it will usually fail to build with the same request error ( but rarely successfully builds with no request errors ).

After trying some combinations of different versions I found that switching to next ( 13.5.3 ) will build even with `useCdn: false` and `cache: 'force-cache'`. 

Also tried the canary branch of next ( v13.5.5-canary.7 ) which seemed to be working ( on local dev ).

**Comment by charlottedamm** [comment] 2023-10-13 07:55
Downgrading to 13.5.3 fixes the build problems for us! Many thanks @ja-iy!

**Comment by alexanderkalachev** [comment] 2023-10-13 11:14
Downgrading to 13.5.3 also works for me without "cache: 'no-store'" and with useCdn: true

**Comment by ja-iy** [comment] 2023-10-13 22:07
Glad it worked for you as well : D, one thing to note is that revalidation behaviour might be broken in next (13.5.3 )

[revalidateTag() works unpredictable](https://github.com/vercel/next.js/issues/55960)

People were mentioning that in 13.5.4 their issue seems to be fixed. 

For me revlidateTag works as expected when building locally with next (13.5.3 ) and the canary (13.5.5-canary.7 ) but when deployed to vercel is unpredictable / doesn't work ( at the moment ).

**Comment by stipsan** [comment] 2024-01-02 17:04
Closing this assuming it's fixed. If it's still a problem feel free to create a new issue that links to this one and we'll dive back in :)

**Closed by stipsan** 2024-01-02 17:04 UTC
